---
apiVersion: v1
kind: Service
metadata:
  name: seed
spec:
  selector:
    app: seed
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seed
  template:
    metadata:
      labels:
        app: seed
    spec:
      imagePullSecrets:
        - name: github-docker-registry
      containers:
        - name: main
          image: docker.pkg.github.com/danielpacak/dev-sec-ops-seed/seed:0.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: "SEED_HTTP_ADDR"
              value: ":8080"
            - name: "SEED_HTTP_READ_TIMEOUT"
              value: "15s"
            - name: "SEED_HTTP_WRITE_TIMEOUT"
              value: "15s"
          ports:
            - name: http-port
              containerPort: 8080
